# Imports
import csv
import random
from operator import le


class csvGenerator:

    COLUMNS = ["first_name", "middle_name", "last_name",
               "phone_number", "email_address", "postal_code",
               "mobile_ad_id", "t_uid"]
    FILES = ["First_Name.txt", "Middle_Name.txt", "Last_Name.txt",
             "Phone_Number.txt", "Email_Address.txt", "Postal_Code.txt",
             "Mobile_AD_ID.txt", "T_UID.txt"]
    DATA = {}
    GeneratorJSON = {"Columns": [], "HeaderFlag": False, "Rows": 0}

    def setForGeneration(self, column, zeroFlag):
        fileIndex = self.COLUMNS.index(column)
        columnConfig = {"name": column, "data": fileIndex, "zeros": zeroFlag}
        self.GeneratorJSON["Columns"].append(columnConfig)

    def generateCSV(self):
        rows = self.GeneratorJSON["Rows"]
        with open("Synthetic Data/Autogenerated.csv", "w", newline='') as file:
            writer = csv.writer(file)
            if(self.GeneratorJSON["HeaderFlag"]):
                writer.writerow(self.COLUMNS)
            while (rows != 0):
                writer.writerow(self.generateRow())
                rows -= 1

    def setData(self):
        for i in range(len(self.COLUMNS)):
            self.DATA[self.COLUMNS[i]] = self.loadData(self.FILES[i])

    def loadData(self, file):
        with open('Data/'+file) as file:
            dataArray = file.read().splitlines()
        return dataArray

    def generateRow(self):
        row = []
        for columnConfig in self.GeneratorJSON["Columns"]:
            row.append(self.getValue(columnConfig))
        return row

    def getValue(self, columnConfig):
        zeroProb = 0
        data = self.DATA[columnConfig["name"]]
        if(columnConfig["zeros"]):
            zeroProb = random.randrange(0, 100, 1)
        if(zeroProb >= 80):
            return ""
        else:
            return random.choice(data)
